# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Gradle@2
    displayName: 'Run initial build with tests'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'
  - script: |
      ./gradlew build staticAnalysis -P staticAnalysisMarker
    displayName: 'Run static analysis'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    continueOnError: true
  - publish: |
      $(Build.SourcesDirectory)/build/reports/staticAnalysis
    artifact: 'Static Analysis Reports'
    displayName: 'Publish static analysis reports'
    condition: eq(variables['Build.Reason'], 'PullRequest')
  - script: |
      ./gradlew build jacocoTestReport
    displayName: 'Generating code coverage report'
  - bash: |
      bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN)
    displayName: 'Upload coverage to codecov.io'
  - task: Gradle@2
    displayName: 'Build executable jar file'
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      tasks: 'shadowJar'
  - script: |
      java -cp crowdin-cli-*.jar picocli.AutoComplete com.crowdin.cli.commands.picocli.RootCommand
    workingDirectory: '$(Build.SourcesDirectory)/build/libs/'
    displayName: 'Generate autocomplete script' 
  - task: CopyFiles@2
    displayName: 'Copy build to Artifact staging directory'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'build/libs/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: build
